

export const appointment=[
    {
        order_id:2422562,
        patient_name:"sam ",
        patient_age:26,
        patient_gender:"F",
        consultation_logo:"",
        consultation_name:"Video",
        consultation_type:"Fist Consultation",
        team_name:"",
        doctor_name:"Anil kumar",
        slot_date:"Jul 3, 2021",
        slot_time:"8:53 AM",
        status_type:"Cencelled",
        invoice_type:"Refunded",
        action_type:""
    },
    {
        order_id:2429657,
        patient_name:"Riju K",
        patient_age:32,
        patient_gender:"M",
        consultation_logo:"",
        consultation_name:"Video",
        consultation_type:"Follow up",
        team_name:"Medical Camp",
        doctor_name:"Greg Ferguson",
        slot_date:"Jul 3, 2021",
        slot_time:"8:53 AM",
        status_type:"No Show",
        invoice_type:"Unpaid",
        action_type:""
    },
    {
        order_id:2422455,
        patient_name:"Prajeesh",
        patient_age:47,
        patient_gender:"M",
        consultation_logo:"",
        consultation_name:"Anytime Consult",
        consultation_type:"",
        team_name:"",
        doctor_name:"Pankaj Dhir",
        slot_date:"Jul 3, 2021",
        slot_time:"8:53 AM",
        status_type:"Completed",
        invoice_type:"Paid",
        action_type:""
    },
    {
        order_id:2421751,
        patient_name:"Nikita Gandhi",
        patient_age:29,
        patient_gender:"F",
        consultation_logo:"",
        consultation_name:"Video",
        consultation_type:"Fist Consultation",
        team_name:"Medical Camp",
        doctor_name:"Sujata Mohan",
        slot_date:"Jul 3, 2021",
        slot_time:"8:53 AM",
        status_type:"Booked",
        invoice_type:"Paid",
        action_type:""
    },
    {
        order_id:2422455,
        patient_name:"Darshan Singh",
        patient_age:36,
        patient_gender:"M",
        consultation_logo:"",
        consultation_name:"In-person",
        consultation_type:"Second Opinion",
        team_name:"",
        doctor_name:"Ram Dayanand",
        slot_date:"Jul 3, 2021",
        slot_time:"8:53 AM",
        status_type:"Completed",
        invoice_type:"Unpaid",
        action_type:""
    },
    {
        order_id:2421751,
        patient_name:"Risha Mahin ",
        patient_age:19,
        patient_gender:"F",
        consultation_logo:"",
        consultation_name:"Video",
        consultation_type:"Fist Consultation",
        team_name:"",
        doctor_name:"Prakash Jhanti ",
        slot_date:"Jul 3, 2021",
        slot_time:"8:53 AM",
        status_type:"Completed",
        invoice_type:"Paid",
        action_type:""
    }
    ]
